# 可更改配置
server.port=8080
server.ip=127.0.0.1
allow.login=true
allow.register=true
mongo.uri=mongodb://localhost:27017
mongo.db=chat
db.type=mongodb
redis.host=localhost
redis.port=6379
redis.password=
